name: Bug Report
description: Report a bug to help us improve Booklore
title: "[Bug] "
labels: [ "bug" ]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the details below so we can investigate and fix the issue.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Quick Check
      options:
        - label: I've searched existing issues and this bug hasn't been reported yet
          required: true

  - type: textarea
    id: description
    attributes:
      label: What Went Wrong?
      description: Give us a clear description of the bug
      placeholder: "Example: When I try to add a book to my 'Want to Read' shelf, the page refreshes but the book doesn't appear on the shelf"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: How Can We Reproduce This?
      description: Walk us through the steps to reproduce the bug
      placeholder: |
        1. Go to the book details page for "The Hobbit"
        2. Click on the "Add to Shelf" dropdown
        3. Select "Want to Read"
        4. Click "Save"
        5. Navigate to the "Want to Read" shelf
        
        Result: The book doesn't appear on the shelf
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What Should Have Happened?
      description: Tell us what you expected to happen instead
      placeholder: "Example: The book should appear on my 'Want to Read' shelf immediately after clicking Save"
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or Error Messages (Optional)
      description: If you have any screenshots or error messages, feel free to share them here
      placeholder: "Just drag and drop images or paste error messages here"

  - type: textarea
    id: solution
    attributes:
      label: Any Ideas on How to Fix This? (Optional)
      description: If you have thoughts on what might be causing this or how to fix it, we'd love to hear them

  - type: textarea
    id: environment
    attributes:
      label: Your Setup
      description: Help us understand your environment
      placeholder: |
        - Booklore Version: v1.1.0
        - OS: macOS Sonoma 14.2
        - Browser: Chrome 120
        - Installation: Docker
        - Storage Type: Local SSD
    validations:
      required: true

