name: Feature Request
description: Suggest a new feature or enhancement for Booklore
title: "[Feature] "
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Please share as much detail as you can to help us understand your suggestion.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Quick Check
      options:
        - label: I've searched existing issues and this feature hasn't been requested yet
          required: true

  - type: textarea
    id: description
    attributes:
      label: What's Your Idea?
      description: Tell us about the feature you'd like to see
      placeholder: "Example: Add a 'Currently Reading' shelf where I can track books I'm reading and see my progress"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Why Would This Be Helpful?
      description: Help us understand the problem this solves or the value it brings
      placeholder: "Example: Right now, it's hard to keep track of multiple books I'm reading at once. Having a dedicated shelf with progress tracking would help me stay organized"
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Anything Else? (Optional)
      description: Feel free to add screenshots, mockups, examples from other apps, or implementation ideas
      placeholder: |
        You might want to include:
        - Screenshots or mockups showing what you envision
        - Examples from other apps you like (Goodreads, StoryGraph, etc.)
        - Ideas for how it could work (progress bars, page counters, etc.)
        - Alternative approaches you've thought about

  - type: dropdown
    id: willing-to-contribute
    attributes:
      label: Want to Help Out?
      description: Let us know if you'd like to be involved in making this happen
      options:
        - "Yes! I'd love to help implement this"
        - "I'm happy to help test and give feedback"
        - "Just sharing the idea for now"
    validations:
      required: true
